name: Scrape SBS Table Monthly

on:
  schedule:
    - cron: '0 2 1 * *' # 1ro de cada mes a las 2AM UTC
  workflow_dispatch: # permite ejecutar manualmente desde GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit scraped data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "Auto scrape SBS data: $(date +'%Y-%m')" || echo "No changes to commit"
          git push
