name: Scrape AFP

on:
  schedule:
    - cron: '0 12 * * *' # todos los días a las 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar scraper
        run: node scraper.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Hacer commit y push si hay cambios
        run: |
          git add data/
          git diff --cached --quiet || git commit -m "📦 Datos actualizados automáticamente"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
